# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('vehicle_id', models.UUIDField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='VALID', max_length=10)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='uploads/compliance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
