# Generated by Django 4.2.23 on 2026-02-14 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('contract_id', models.UUIDField()),
                ('paid_from', models.CharField(max_length=255)),
                ('paid_to', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('INSTALLMENT', 'Installment'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty'), ('INSURANCE', 'Insurance'), ('SERVICE', 'Service'), ('REPAIR', 'Repair'), ('OTHER', 'Other')], max_length=20)),
                ('mpesa_code', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_paid', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='uploads/payments/')),
            ],
        ),
    ]
