# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('rider_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('revenue_model', models.CharField(choices=[('FIXED', 'Fixed Daily Remittance'), ('PERCENTAGE', 'Percentage Share'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terms', models.TextField()),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='uploads/contracts/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
