# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=32, unique=True)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('engine_number', models.CharField(blank=True, max_length=64, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=64, null=True)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hire_purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_period', models.PositiveIntegerField(help_text='Number of months')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_REPAIR', 'Under Repair'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/vehicles/')),
                ('total_kilometers', models.PositiveIntegerField(default=0)),
                ('in_service_days', models.PositiveIntegerField(default=0)),
                ('off_days', models.PositiveIntegerField(default=0)),
                ('risk_assessment', models.TextField(blank=True, null=True)),
                ('asset_recovery_status', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
