# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('TOTAL_FLEET_VALUE', 'Total Fleet Value'), ('OUTSTANDING_LIABILITIES', 'Outstanding Liabilities'), ('MONTHLY_REVENUE', 'Monthly Revenue'), ('NET_PROFIT', 'Net Profit'), ('MOST_PROFITABLE_VEHICLE', 'Most Profitable Vehicle'), ('HIGHEST_MAINTENANCE_VEHICLE', 'Highest Maintenance Vehicle'), ('COMPLIANCE_ALERTS', 'Compliance Alerts'), ('CONTRACT_EXPIRY_ALERTS', 'Contract Expiry Alerts')], max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('VEHICLE_FINANCIAL', 'Vehicle Financial Report'), ('MONTHLY_PROFIT', 'Monthly Profit Report'), ('ANNUAL_SUMMARY', 'Annual Summary'), ('RIDER_STATEMENT', 'Rider Statement'), ('HIRE_PURCHASE_STATEMENT', 'Hire Purchase Statement'), ('MAINTENANCE_SUMMARY', 'Maintenance Summary'), ('COMPLIANCE_REPORT', 'Compliance Report'), ('CONTRACT_AGREEMENT', 'Contract Agreement'), ('EXPENSE_SUMMARY', 'Expense Summary'), ('FLEET_PERFORMANCE', 'Fleet Performance Report')], max_length=32)),
                ('generated_for', models.CharField(blank=True, max_length=128, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/reports/')),
            ],
        ),
    ]
