# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('component_name', models.CharField(max_length=128)),
                ('supplier', models.CharField(max_length=128)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('failure_frequency', models.PositiveIntegerField(default=0)),
                ('mechanic', models.CharField(blank=True, max_length=128, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='uploads/maintenance/components/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DowntimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('MAINTENANCE', 'Maintenance'), ('ACCIDENT', 'Accident'), ('REGULATORY', 'Regulatory'), ('PERSONAL_LEAVE', 'Personal Leave'), ('OTHER', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('REPAIR', 'Repair'), ('SPARE_PART', 'Spare Part'), ('INSURANCE', 'Insurance'), ('LICENSE', 'License'), ('PENALTY', 'Penalty'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='uploads/maintenance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OdometerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('service_type', models.CharField(max_length=64)),
                ('mechanic', models.CharField(max_length=128)),
                ('service_date', models.DateField()),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='uploads/maintenance/services/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
