# Generated by Django 4.2.23 on 2026-02-14 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('national_id', models.CharField(max_length=32, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='uploads/riders/photos/')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='uploads/riders/licenses/')),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='uploads/riders/id_copies/')),
                ('assigned_vehicle', models.UUIDField(blank=True, null=True)),
                ('assignment_history', models.JSONField(blank=True, help_text='List of previous vehicle assignments', null=True)),
                ('compliance_history', models.JSONField(blank=True, help_text='List of compliance events or issues', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
